### ISSUE TITLE
Dedicated Server stuck preparing spawn area or crashes

### ISSUE THREAD

**Issue by Goldenschmidt** [EtiTheSpirit/TheOriMod#4]
**What happens?**
The server boots up normally, but immediately gets stuck between 96% and 99% completed. It does not budge afterwards, even after a long while.

**How do I cause it?**
Install a dedicated Forge server in any empty folder of your choice, using the Forge installer. When that is done, Navigate to that folder, and click the **Run.bat** file. Click a button on the keyboard when it prompts you to, and then open the new **EULA** text file in the server folder. Change the **False** to **True**, and save it. Run the **Run.bat** file again, and wait till it has generated a world. Once done, write **stop** and wait till it prompts you to press a key.
A bunch of new folders have appeared, but the most important of them all is the **mods** folder. Open it and put in the **Spirit mod** file. Launch the server again.

One of two things will happen then.
**1:** 
If you delete the world folder before launching the server for the last time, it will get stuck between 96% and 99% on Preparing Spawn Area. (Log 1)

**2:**
If you do not delete the world folder before launching the server for the last time, it will crash once it finished booting up the server. (Log 2)

**Is this bug so bad that you find it nearly impossible to play?**
Yes. If you want to play it on a dedicated server.

**Log file**
[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10356251/debug.log) Log 1
[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10356286/debug.log) Log 2

**Comment by EtiTheSpirit** [comment]
Hey, just following up here. This as well as #2 and #3 are both fixed in the ~~1.3.0~~ (edit: 2.0.0) update, which is in its final testing phase.

Hopefully this update should be out soon. Thank you for the reports.

**Comment by Goldenschmidt** [comment]
I will give them a test with my friend, and update you on it if the issues are fixed, once the files has been uploaded. Thank you for the quick response.

**Comment by EtiTheSpirit** [comment]
Alright. 2.0.0-RC1 is out now. https://www.curseforge.com/minecraft/mc-mods/the-ori-mod/files/4323922

This was a huge update that added a lot of new stuff (including some worldgen) so that's part of why it took so long to get it all out. This *should* run on servers okay, but let me know if this issue or any of the others you reported persist.

Sorry for the troubles, hopefully this should fix it. Remember to back up your world. You may also need to make use of the new `/spirit ability ...` command (because abilities can be toggled now).

**Comment by Goldenschmidt** [comment]
So gave it a whirl on a dedicated server, and it still causes issues launching the server.

[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10386391/debug.log) While generating a new world with the mod.


[debug.log](https://github.com/EtiTheSpirit/TheOriMod/files/10386423/debug.log) While launching server on pre-created world.

**Comment by EtiTheSpirit** [comment]
The first log seems to be truncated (cuts off early). The second one indicates an issue in a class that is no longer used, so I can just remove it entirely.

The new update is here. https://www.curseforge.com/minecraft/mc-mods/the-ori-mod/files/4327526

**Comment by Goldenschmidt** [comment]
RC2 have fixed the server from outright crashing by its presence alone, and can now launch without causing it to crash.

However, issue #2 is still present. Will post the Debug file on that issue, as it is not relevant with issue #4.
